<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Book;
use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    /**
     * @param array $filters
     * @return array
     */
    public function getAllBooks($filters = [])
    {
        $allBooksQueryBuilder = $this->getEntityManager()->getRepository(Book::class)
            ->createQueryBuilder('book')
            ->select('book,cat')
            ->innerJoin('book.category', 'cat')
            ->where('book.status = :status')
            ->setParameter('status', '1');

        return $allBooksQueryBuilder->getQuery()->getResult();
    }

    public function getBookArray($bookId)
    {
        $bookQueryBuilder = $this->getEntityManager()->getRepository(Book::class)
            ->createQueryBuilder('book');

        return $bookQueryBuilder->select('book')
            ->where('book.id= :id')
            ->setParameter('id', $bookId)
            ->getQuery()
            ->getResult(1);
    }
}
